name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: sh -c 'ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST_NAME }}  >> ~/.ssh/known_hosts'; sh -c 'ssh-keyscan -p ${{ secrets.PROXY_SSH_PORT }} -H ${{ secrets.PROXY_SSH_HOST_NAME }}  >> ~/.ssh/known_hosts'; sh -c 'echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config'

      - name: Deploy with rsync
        run: rsync -auvPz ./ ${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/bonne-coordination/
